### ISSUE TITLE
Add a CHANGELOG.md

### ISSUE THREAD

**Issue by davetgreen** [mkdo/kapow-core#12]
The repo will need a changelog adding once initial development has been completed, in a similar format to the one found in each of the other module repos.

**Comment by mwtsn** [comment]
@davetgreen I understand this is auto generated right? How does one do this?

**Comment by davetgreen** [comment]
@mwtsn nah it's still manual. I was toying with auto generation, got some ideas about how we can do it but won't happen yet.

**Comment by davetgreen** [comment]
Completed. File added with a basic head start, needs proper treatment at some point as do the others.
