### ISSUE TITLE
Remove Customizer Javascript files & enqueues

### ISSUE THREAD

**Issue by davetgreen** [mkdo/kapow-core#5]
As we're handling all Customizer related PHP/JS in the theme, all the Customizer Javascripts in `assets/js` can be removed, as well as the asset enqueues.

**Comment by mwtsn** [comment]
I disagree @davetgreen there may be some that we need to add in global for everything we do (perhaps something like a credit logo?)

At the moment it is there but doesn't run, so its harmless leaving as is.

**Comment by davetgreen** [comment]
@mwtsn I guess a generic contact details section could be a global thing, with tel, fax, email, address etc. Probably need to create a new ticket and scope out what globals we want

**Comment by davetgreen** [comment]
@mwtsn okay closing this, we'll keep for globals.
