### ISSUE TITLE
Set a default location for render view overrides

### ISSUE THREAD

**Issue by davetgreen** [mkdo/kapow-core#9]
It would be fantastic if the render view trait could check the `template-parts` folder in the currently active theme as a default/fallback, as that's where we do place the overrides 90% of the time.

**Comment by mwtsn** [comment]
@davetgreen to do this you just need to enable the appropriate filters in your theme. As this could potentially be used for any theme, I will not do the check automatically because:

- Checks slow down queries
- There are filters that enable this already
- There are currently no views in the build
